"use client";

import { useEffect, useState } from 'react';
import { ArrowLeft, BookOpen, FileText, Mail, Wrench } from 'lucide-react';

type ExploreData = { tools: Array<{ name: string; purpose: string }>; people: Array<{ name: string; role: string; email?: string; expertise?: string }>; documents: Array<{ id: number; title: string; status: string }> };

export default function ExplorePage() {
  const [data, setData] = useState<ExploreData>({ tools: [], people: [], documents: [] });
  useEffect(() => { fetch('/api/explore').then((response) => response.json()).then(setData); }, []);
  return <main id="main-content" className="dashboard-grid min-h-screen px-4 py-6 text-slate-900 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><a href="/home" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft size={16} /> Back to Sherpa</a><header className="mt-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Explore</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Find your way around.</h1><p className="mt-3 max-w-xl text-slate-600">Browse the tools, people, and knowledge behind your onboarding experience.</p></header><div className="mt-8 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center gap-3"><Wrench className="text-primary" size={20} /><h2 className="text-xl font-bold">Tools</h2></div><div className="mt-5 space-y-3">{data.tools.map((tool) => <div key={tool.name} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{tool.name}</p><p className="mt-1 text-sm text-slate-500">{tool.purpose}</p></div>)}</div></section><section className="rounded-2xl bg-primary p-6 text-white"><div className="flex items-center gap-3"><Mail className="text-amber-300" size={20} /><h2 className="text-xl font-bold">People</h2></div><div className="mt-5 space-y-3">{data.people.map((person) => <div key={person.name} className="border-b border-white/15 pb-3"><p className="font-semibold">{person.name}</p><p className="mt-1 text-sm text-slate-200">{person.role}</p><p className="mt-2 text-xs text-amber-300">{person.email || person.expertise}</p></div>)}</div></section><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center gap-3"><BookOpen className="text-primary" size={20} /><h2 className="text-xl font-bold">Knowledge</h2></div><div className="mt-5 space-y-3">{data.documents.map((document) => <div key={document.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-4"><FileText size={17} className="text-slate-400" /><div><p className="font-semibold">{document.title}</p><p className="text-xs text-slate-500">{document.status}</p></div></div>)}{data.documents.length === 0 ? <p className="text-sm text-slate-500">Upload documents from the admin workspace.</p> : null}</div></section></div></div></main>;
}
